// <auto-generated>
// This file was generated by DTOMaker.CSRecord.
// NuGet: https://www.nuget.org/packages/DTOMaker.CSRecord
// Warning: Changes made to this file will be lost if re-generated.
// </auto-generated>
//##if(false) {
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0162 // Unreachable code detected
//##}
#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#nullable enable
using DataFac.Memory;
using DTOMaker.Runtime;
using DTOMaker.Runtime.CSRecord;
using System;

//##if (false) {
using T_MemberType_ = System.Int32;
namespace T_MemberTypeNameSpace_
{
    public interface IT_MemberTypeName_ { }
}
namespace T_MemberTypeNameSpace_.CSRecord
{
    public record T_MemberTypeName_ : EntityBase, IT_MemberTypeName_
    {
        private const int T_EntityId_ = 1;
        private static readonly T_MemberTypeName_ _empty = new T_MemberTypeName_();
        public static T_MemberTypeName_ Empty => _empty;
        public static T_MemberTypeName_ CreateFrom(IT_MemberTypeName_ source) => throw new NotImplementedException();
        public T_MemberTypeName_() { }
        public T_MemberTypeName_(IT_MemberTypeName_ source) { }
        protected override int OnGetEntityId() => T_EntityId_;
    }
}
namespace T_BaseNameSpace_
{
    public interface IT_BaseName_ { }
}
namespace T_BaseNameSpace_.CSRecord
{
    public abstract record T_BaseName_ : EntityBase, IT_BaseName_, IEquatable<T_BaseName_>
    {
        public T_BaseName_() { }
        public T_BaseName_(IT_BaseName_ source) : base(source) { }
        public T_MemberType_ BaseField1 { get; set; }
    }
}
namespace T_NameSpace_
{
    public interface IT_EntityName_ : T_BaseNameSpace_.IT_BaseName_
    {
        T_MemberType_? T_NullableScalarMemberName_ { get; }
        T_MemberType_ T_RequiredScalarMemberName_ { get; }
        ReadOnlyMemory<T_MemberType_> T_VectorMemberName_ { get; }
        T_MemberTypeNameSpace_.IT_MemberTypeName_? T_NullableEntityMemberName_ { get; }
        T_MemberTypeNameSpace_.IT_MemberTypeName_ T_RequiredEntityMemberName_ { get; }
        Octets? T_NullableBinaryMemberName_ { get; }
        Octets T_RequiredBinaryMemberName_ { get; }
        string? T_NullableStringMemberName_ { get; }
        string T_RequiredStringMemberName_ { get; }
    }
}
//##}
namespace T_NameSpace_.CSRecord
{
    //##if (false) {
    //##}
    public partial record T_EntityName_ : T_BaseNameSpace_.CSRecord.T_BaseName_, IT_EntityName_, IEquatable<T_EntityName_>
    {
        // Derived entities: T_DerivedEntityCount_
        //##foreach (var derived in entity.DerivedEntities) {
        //##using var _ = NewScope(derived);
        // - T_EntityName_
        //##}
        //##if (false) {
        private const string T_MemberObsoleteMessage_ = null;
        private const bool T_MemberObsoleteIsError_ = false;
        private const int T_MemberDefaultValue_ = 0;
        private const int T_EntityId_ = 1;
        //##}

        public new const int EntityId = T_EntityId_;

        private static T_EntityName_ CreateEmpty()
        {
            var empty = new T_EntityName_();
            return empty;
        }
        private static readonly T_EntityName_ _empty = CreateEmpty();
        public static T_EntityName_ Empty => _empty;

        public new static T_EntityName_ CreateFrom(T_EntityName_ source)
        {
            if (source.IsFrozen) return source;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_NameSpace_.CSRecord.T_EntityName_ source2 => new T_NameSpace_.CSRecord.T_EntityName_(source2),
                //##}
                _ => new T_NameSpace_.CSRecord.T_EntityName_(source)
            };
        }

        public new static T_EntityName_ CreateFrom(T_NameSpace_.IT_EntityName_ source)
        {
            if (source is T_EntityName_ concrete && concrete.IsFrozen) return concrete;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_NameSpace_.IT_EntityName_ source2 => new T_NameSpace_.CSRecord.T_EntityName_(source2),
                //##}
                _ => new T_NameSpace_.CSRecord.T_EntityName_(source)
            };
        }

        protected override int OnGetEntityId() => EntityId;

        public T_EntityName_() { }
        public T_EntityName_(IT_EntityName_ source) : base(source)
        {
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(member);
            //##switch(member.Kind) {
            //##case MemberKind.Scalar:
            //##if (member.IsNullable) {
            _T_NullableScalarMemberName_ = source.T_NullableScalarMemberName_;
            //##} else {
            _T_RequiredScalarMemberName_ = source.T_RequiredScalarMemberName_;
            //##}
            //##break;
            //##case MemberKind.Vector:
            _T_VectorMemberName_ = source.T_VectorMemberName_;
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeNameSpace_.CSRecord.T_MemberTypeName_.CreateFrom(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeNameSpace_.CSRecord.T_MemberTypeName_.CreateFrom(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##} // foreach
        }

        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(member);
        //##switch(member.Kind) {
        //##case MemberKind.Scalar:
        //##if (member.IsNullable) {
        private T_MemberType_? _T_NullableScalarMemberName_;
        //##} else {
        private T_MemberType_ _T_RequiredScalarMemberName_ = T_MemberDefaultValue_;
        //##}
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        //##if (member.IsNullable) {
        public T_MemberType_? T_NullableScalarMemberName_
        {
            get => _T_NullableScalarMemberName_;
            init => _T_NullableScalarMemberName_ = value;
        }
        //##} else {
        public T_MemberType_ T_RequiredScalarMemberName_
        {
            get => _T_RequiredScalarMemberName_;
            init => _T_RequiredScalarMemberName_ = value;
        }
        //##}
        //##break;
        //##case MemberKind.Vector:
        private ReadOnlyMemory<T_MemberType_> _T_VectorMemberName_;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public ReadOnlyMemory<T_MemberType_> T_VectorMemberName_
        {
            get => _T_VectorMemberName_;
            init => _T_VectorMemberName_ = value;
        }
        //##break;
        //##case MemberKind.Entity:
        //##if (member.IsNullable) {
        private T_MemberTypeNameSpace_.CSRecord.T_MemberTypeName_? _T_NullableEntityMemberName_;
        public T_MemberTypeNameSpace_.CSRecord.T_MemberTypeName_? T_NullableEntityMemberName_
        {
            get => _T_NullableEntityMemberName_;
            init => _T_NullableEntityMemberName_ = value;
        }
        T_MemberTypeNameSpace_.IT_MemberTypeName_? IT_EntityName_.T_NullableEntityMemberName_ => T_NullableEntityMemberName_;
        //##} else {
        private T_MemberTypeNameSpace_.CSRecord.T_MemberTypeName_ _T_RequiredEntityMemberName_ = T_MemberTypeNameSpace_.CSRecord.T_MemberTypeName_.Empty;
        public T_MemberTypeNameSpace_.CSRecord.T_MemberTypeName_ T_RequiredEntityMemberName_
        {
            get => _T_RequiredEntityMemberName_;
            init => _T_RequiredEntityMemberName_ = value;
        }
        T_MemberTypeNameSpace_.IT_MemberTypeName_ IT_EntityName_.T_RequiredEntityMemberName_ => T_RequiredEntityMemberName_;
        //##}
        //##break;
        //##case MemberKind.Binary:
        //##if (member.IsNullable) {
        private Octets? _T_NullableBinaryMemberName_;
        public Octets? T_NullableBinaryMemberName_
        {
            get => _T_NullableBinaryMemberName_;
            init => _T_NullableBinaryMemberName_ = value;
        }
        //##} else {
        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;
        public Octets T_RequiredBinaryMemberName_
        {
            get => _T_RequiredBinaryMemberName_;
            init => _T_RequiredBinaryMemberName_ = value;
        }
        //##}
        //##break;
        //##case MemberKind.String:
        //##if (member.IsNullable) {
        private string? _T_NullableStringMemberName_;
        public string? T_NullableStringMemberName_
        {
            get => _T_NullableStringMemberName_;
            init => _T_NullableStringMemberName_ = value;
        }
        //##} else {
        private string _T_RequiredStringMemberName_ = string.Empty;
        public string T_RequiredStringMemberName_
        {
            get => _T_RequiredStringMemberName_;
            init => _T_RequiredStringMemberName_ = value;
        }
        //##}
        //##break;
        //##default:
        //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
        //##break;
        //##} // switch

        //##}
    }
}