// <auto-generated>
// This file was generated by DTOMaker.MemBlocks.
// NuGet: https://www.nuget.org/packages/DTOMaker.MemBlocks
// Warning: Changes made to this file will be lost if re-generated.
// </auto-generated>
//##if(false) {
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0162 // Unreachable code detected
//##}
#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#nullable enable
using System;
using System.Buffers;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using DataFac.Memory;
using DTOMaker.Runtime;
using DTOMaker.Runtime.MemBlocks;
using DataFac.Storage;

//##if(false) {
using T_MemberType_ = System.Int32;
namespace DataFac.Memory
{
    public static class Codec_T_MemberType__T_MemberBELE_
    {
        public static T_MemberType_ ReadFromSpan(ReadOnlySpan<byte> source) => Codec_Int32_LE.ReadFromSpan(source);
        public static void WriteToSpan(Span<byte> source, T_MemberType_ value) => Codec_Int32_LE.WriteToSpan(source, value);
    }
}
namespace T_MemberTypeNameSpace_
{
    public interface IT_MemberTypeName_ : IMemBlocksEntity
    {
        Int64 Field1 { get; set; }
    }
}
namespace T_MemberTypeNameSpace_.MemBlocks
{
    public sealed class T_MemberTypeName_ : EntityBase, IT_MemberTypeName_
    {
        private const int ClassHeight = 1;
        private const int BlockOffset = 64;
        private const int BlockLength = 64;
        private const long StructureCode = 0x0662;
        private static readonly Guid EntityGuid = new Guid("9bb68dc1-8b05-4e19-80fd-c1fb946ffd8d");
        private static readonly BlockHeader _header = BlockHeader.CreateNew(StructureCode, EntityGuid);

        public static T_MemberTypeName_ CreateFrom(T_MemberTypeName_ source)
        {
            if (source.IsFrozen) return source;
            return new T_MemberTypeName_(source);
        }
        public static T_MemberTypeName_ CreateFrom(IT_MemberTypeName_ source)
        {
            if (source is T_MemberTypeName_ concrete && concrete.IsFrozen) return concrete;
            return new T_MemberTypeName_(source);
        }
        public static T_MemberTypeName_ CreateFrom(ReadOnlyMemory<byte> buffer)
        {
            return new T_MemberTypeName_(buffer);
        }
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;
        public T_MemberTypeName_() : base(_header)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
        }
        public T_MemberTypeName_(T_MemberTypeName_ source) : base(_header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
        }
        public T_MemberTypeName_(IT_MemberTypeName_ source) : base(_header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
            this.Field1 = source.Field1;
        }
        public T_MemberTypeName_(ReadOnlyMemory<byte> buffer) : base(_header, buffer)
        {
            _readonlyLocalBlock = _readonlyTotalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = Memory<byte>.Empty;
        }

        protected override IFreezable OnPartCopy() => throw new NotImplementedException();
        protected override string OnGetEntityId() => "T_MemberTypeName_";
        protected override int OnGetClassHeight() => ClassHeight;
        protected override ValueTask OnPack(IDataStore dataStore) => default;
        protected override ValueTask OnUnpack(IDataStore dataStore, int depth) => default;

        public Int64 Field1
        {
            get => Codec_Int64_LE.ReadFromSpan(_readonlyLocalBlock.Slice(0, 8).Span);
            set => Codec_Int64_LE.WriteToSpan(_writableLocalBlock.Slice(0, 8).Span, IfNotFrozen(value));
        }
    }
}
namespace T_BaseNameSpace_.MemBlocks
{
    public interface IT_BaseName_
    {
        T_MemberType_ BaseField1 { get; set; }
    }
    public class T_BaseName_ : EntityBase, IT_BaseName_, IEquatable<T_BaseName_>
    {
        private const int ClassHeight = 1;
        private const int BlockOffset = 64;
        private const int BlockLength = 64;
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;

        public new const string EntityId = "T_BaseName_";

        protected override string OnGetEntityId() => "_undefined_";
        protected override int OnGetClassHeight() => ClassHeight;

        protected override void OnFreeze()
        {
            base.OnFreeze();
        }

        protected override ValueTask OnPack(IDataStore dataStore)
        {
            return base.OnPack(dataStore);
        }

        protected override ValueTask OnUnpack(IDataStore dataStore, int depth)
        {
            return base.OnUnpack(dataStore, depth);
        }

        protected T_BaseName_(BlockHeader header) : base(header)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
        }

        protected T_BaseName_(BlockHeader header, T_BaseName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
        }

        protected T_BaseName_(BlockHeader header, IT_BaseName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
            this.BaseField1 = source.BaseField1;
        }

        protected T_BaseName_(BlockHeader header, ReadOnlyMemory<byte> buffer) : base(header, buffer)
        {
            _readonlyLocalBlock = _readonlyTotalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = Memory<byte>.Empty;
        }

        private const int T_FieldOffset_ = 4;
        private const int T_FieldLength_ = 4;

        public T_MemberType_ BaseField1
        {
            get => (T_MemberType_)Codec_T_MemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span);
            set => Codec_T_MemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span, IfNotFrozen(value));
        }

        public bool Equals(T_BaseName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!_readonlyTotalBlock.Span.SequenceEqual(other._readonlyTotalBlock.Span)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_BaseName_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
    }
}
namespace T_NameSpace_
{
    public interface IT_EntityName_ : T_BaseNameSpace_.MemBlocks.IT_BaseName_
    {
        T_MemberType_ T_ScalarMemberName_ { get; set; }
        ReadOnlyMemory<T_MemberType_> T_VectorMemberName_ { get; set; }
        T_MemberTypeNameSpace_.IT_MemberTypeName_? T_NullableEntityMemberName_ { get; set; }
        T_MemberTypeNameSpace_.IT_MemberTypeName_ T_RequiredEntityMemberName_ { get; set; }
        Octets? T_NullableBinaryMemberName_ { get; set; }
        Octets T_RequiredBinaryMemberName_ { get; set; }
    }
}
//##}
namespace T_NameSpace_.MemBlocks
{
    public partial class T_EntityName_ : T_BaseNameSpace_.MemBlocks.T_BaseName_, IT_EntityName_, IEquatable<T_EntityName_>
    {
        // Derived entities: T_DerivedEntityCount_
        //##foreach(var derived in entity.DerivedEntities) {
        //##using var _ = NewScope(derived);
        // - T_EntityName_
        //##}

        //##if(false) {
        private const int T_ClassHeight_ = 2;
        private const int T_BlockOffset_ = 128;
        private const int T_BlockLength_ = 512;
        private const bool T_MemberObsoleteIsError_ = false;
        private const long T_BlockStructureCode_ = 0x0962;
        private static readonly Guid T_EntityGuid_ = new Guid("341c6631-30ba-482b-b580-7c1c2c9ff182");
        //##}
        private const long BlockStructureCode = T_BlockStructureCode_;
        private const int ClassHeight = T_ClassHeight_;
        private const int BlockOffset = T_BlockOffset_;
        private const int BlockLength = T_BlockLength_;
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;

        public new const string EntityId = "T_EntityId_";
        private static readonly Guid EntityGuid = T_EntityGuid_;
        private static readonly BlockHeader _header = BlockHeader.CreateNew(BlockStructureCode, EntityGuid);

        public new static T_EntityName_ CreateFrom(T_EntityName_ source)
        {
            if (source.IsFrozen) return source;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_NameSpace_.MemBlocks.T_EntityName_ source2 => new T_NameSpace_.MemBlocks.T_EntityName_(source2),
                //##}
                _ => new T_NameSpace_.MemBlocks.T_EntityName_(source)
            };
        }

        public new static T_EntityName_ CreateFrom(T_NameSpace_.IT_EntityName_ source)
        {
            if (source is T_EntityName_ concrete && concrete.IsFrozen) return concrete;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_NameSpace_.IT_EntityName_ source2 => new T_NameSpace_.MemBlocks.T_EntityName_(source2),
                //##}
                _ => new T_NameSpace_.MemBlocks.T_EntityName_(source)
            };
        }

        public new static T_EntityName_ CreateFrom(ReadOnlyMemory<byte> buffer)
        {
            BlockHeader header = BlockHeader.ParseFrom(buffer);
            string entityIdStr = header.EntityGuid.ToString("D");
            return entityIdStr switch
            {
                //##foreach(var derived in entity.DerivedEntities) {
                //##using var _ = NewScope(derived);
                T_NameSpace_.MemBlocks.T_EntityName_.EntityId => new T_NameSpace_.MemBlocks.T_EntityName_(buffer),
                //##}
                _ => new T_NameSpace_.MemBlocks.T_EntityName_(buffer)
            };
        }

        protected override string OnGetEntityId() => EntityId;
        protected override int OnGetClassHeight() => ClassHeight;

        protected override IFreezable OnPartCopy() => new T_EntityName_(this);

        protected override void OnFreeze()
        {
            base.OnFreeze();
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(member);
            //##switch(member.Kind) {
            //##case MemberKind.Scalar:
            //##break;
            //##case MemberKind.Vector:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_?.Freeze();
            //##} else {
            _T_RequiredEntityMemberName_?.Freeze();
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        protected override async ValueTask OnPack(IDataStore dataStore)
        {
            await base.OnPack(dataStore);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(member);
            //##switch(member.Kind) {
            //##case MemberKind.Scalar:
            //##break;
            //##case MemberKind.Vector:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            await T_NullableEntityMemberName__Pack(dataStore);
            //##} else {
            await T_RequiredEntityMemberName__Pack(dataStore);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            await T_NullableBinaryMemberName__Pack(dataStore);
            //##} else {
            await T_RequiredBinaryMemberName__Pack(dataStore);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        protected override async ValueTask OnUnpack(IDataStore dataStore, int depth)
        {
            await base.OnUnpack(dataStore, depth);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(member);
            //##switch(member.Kind) {
            //##case MemberKind.Scalar:
            //##break;
            //##case MemberKind.Vector:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            await T_NullableEntityMemberName__Unpack(dataStore, depth);
            //##} else {
            await T_RequiredEntityMemberName__Unpack(dataStore, depth);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            await T_NullableBinaryMemberName__Unpack(dataStore, depth);
            //##} else {
            await T_RequiredBinaryMemberName__Unpack(dataStore, depth);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        // -------------------- field map -----------------------------
        //  Seq.  Off.  Len.  N.    Type    End.  Name
        //  ----  ----  ----  ----  ------- ----  -------
        //##foreach(var member in entity.Members) {
        //##using var _ = NewScope(member);
        //  T_MemberSequenceR4_  T_FieldOffsetR4_  T_FieldLengthR4_  T_ArrayLengthR4_  T_MemberTypeL7_ T_MemberBELE_    T_MemberName_
        //##}
        // ------------------------------------------------------------

        protected T_EntityName_(BlockHeader header) : base(header)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
        }
        public T_EntityName_() : base(_header)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
        }

        protected T_EntityName_(BlockHeader header, T_EntityName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
        }
        public T_EntityName_(T_EntityName_ source) : base(_header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
        }

        protected T_EntityName_(BlockHeader header, IT_EntityName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
            //##foreach(var member in entity.Members) {
            //##using var _ = NewScope(member);
            //##switch(member.Kind) {
            //##case MemberKind.Scalar:
            this.T_ScalarMemberName_ = source.T_ScalarMemberName_;
            //##break;
            //##case MemberKind.Vector:
            this.T_VectorMemberName_ = source.T_VectorMemberName_;
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_.CreateFrom(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_.CreateFrom(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        public T_EntityName_(IT_EntityName_ source) : base(_header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = _writableTotalBlock.Slice(BlockOffset, BlockLength);
            //##foreach(var member in entity.Members) {
            //##using var _ = NewScope(member);
            //##switch(member.Kind) {
            //##case MemberKind.Scalar:
            this.T_ScalarMemberName_ = source.T_ScalarMemberName_;
            //##break;
            //##case MemberKind.Vector:
            this.T_VectorMemberName_ = source.T_VectorMemberName_;
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_.CreateFrom(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_.CreateFrom(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        protected T_EntityName_(BlockHeader header, ReadOnlyMemory<byte> buffer) : base(header, buffer)
        {
            _readonlyLocalBlock = _readonlyTotalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = Memory<byte>.Empty;
        }
        public T_EntityName_(ReadOnlyMemory<byte> buffer) : base(_header, buffer)
        {
            _readonlyLocalBlock = _readonlyTotalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = Memory<byte>.Empty;
        }

        //##if(false) {
        //private const int T_FieldOffset_ = 64;
        private const int T_ScalarFieldOffset_ = 0;
        private const int T_VectorFieldOffset_ = 32;
        private const int T_NullableEntityFieldOffset_ = 64;
        private const int T_RequiredEntityFieldOffset_ = 128;
        private const int T_NullableBinaryFieldOffset_ = 192;
        private const int T_RequiredBinaryFieldOffset_ = 256;
        private const int T_FieldLength_ = 8;
        private const bool T_IsBigEndian_ = false;
        private const int T_ArrayLength_ = 4;
        //##}
        //##foreach(var member in entity.Members) {
        //##using var _ = NewScope(member);
        //##switch(member.Kind) {
        //##case MemberKind.Scalar:
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberType_ T_ScalarMemberName_
        {
            get => Codec_T_MemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_ScalarFieldOffset_, T_FieldLength_).Span);
            set => Codec_T_MemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_ScalarFieldOffset_, T_FieldLength_).Span, IfNotFrozen(value));
        }
        //##break;
        //##case MemberKind.Vector:
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public ReadOnlyMemory<T_MemberType_> T_VectorMemberName_
        {
            get
            {
                var sourceSpan = _readonlyLocalBlock.Slice(T_VectorFieldOffset_, T_FieldLength_ * T_ArrayLength_).Span;
                //##if(member.FieldLength == 1) {
                return MemoryMarshal.Cast<byte, T_MemberType_>(sourceSpan).ToArray(); // todo alloc!
                //##} else {
                if (BitConverter.IsLittleEndian != T_IsBigEndian_)
                {
                    // endian match
                    return MemoryMarshal.Cast<byte, T_MemberType_>(sourceSpan).ToArray(); // todo alloc!
                }
                else
                {
                    // endian mismatch - decode each element
                    var target = new T_MemberType_[T_ArrayLength_]; // todo alloc!
                    Span<T_MemberType_> targetSpan = target.AsSpan();
                    for (int i = 0; i < T_ArrayLength_; i++)
                    {
                        var elementSpan = sourceSpan.Slice(T_FieldLength_ * i, T_FieldLength_);
                        targetSpan[i] = Codec_T_MemberType__T_MemberBELE_.ReadFromSpan(elementSpan);
                    }
                    return target;
                }
                //##}
            }

            set
            {
                ThrowIfFrozen();
                var targetSpan = _writableLocalBlock.Slice(T_VectorFieldOffset_, T_FieldLength_ * T_ArrayLength_).Span;
                targetSpan.Clear();
                //##if(member.FieldLength == 1) {
                value.Span.CopyTo(MemoryMarshal.Cast<byte, T_MemberType_>(targetSpan));
                //##} else {
                if (BitConverter.IsLittleEndian != T_IsBigEndian_)
                {
                    // endian match
                    value.Span.CopyTo(MemoryMarshal.Cast<byte, T_MemberType_>(targetSpan));
                }
                else
                {
                    // endian mismatch - encode each element
                    var sourceSpan = value.Span;
                    for (int i = 0; i < sourceSpan.Length; i++)
                    {
                        var elementSpan = targetSpan.Slice(T_FieldLength_ * i, T_FieldLength_);
                        Codec_T_MemberType__T_MemberBELE_.WriteToSpan(elementSpan, sourceSpan[i]);
                    }
                }
                //##}
            }
        }
        //##break;
        //##case MemberKind.Entity:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableEntityMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = default;
            if (_T_NullableEntityMemberName_ is not null)
            {
                await _T_NullableEntityMemberName_.Pack(dataStore);
                var buffer = _T_NullableEntityMemberName_.GetBuffer();
                var blob = BlobData.UnsafeWrap(buffer);
                blobId = await dataStore.PutBlob(blob);
            }
            Codec_BlobId_NE.WriteToSpan(_writableLocalBlock.Slice(T_NullableEntityFieldOffset_, 64).Span, blobId);
        }
        private async ValueTask T_NullableEntityMemberName__Unpack(IDataStore dataStore, int depth)
        {
            _T_NullableEntityMemberName_ = null;
            BlobIdV1 blobId = Codec_BlobId_NE.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableEntityFieldOffset_, 64).Span);
            if (!blobId.IsEmpty)
            {
                BlobData? blob = await dataStore.GetBlob(blobId);
                if (blob is null) throw new InvalidDataException($"Blob not found: {blobId}");
                _T_NullableEntityMemberName_ = T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_.CreateFrom(blob.Value.Memory);
                await _T_NullableEntityMemberName_.Unpack(dataStore, depth - 1);
            }
        }
        private T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_? _T_NullableEntityMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_? T_NullableEntityMemberName_
        {
            get => IfUnpacked(_T_NullableEntityMemberName_);
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeNameSpace_.IT_MemberTypeName_? IT_EntityName_.T_NullableEntityMemberName_
        {
            get => IfUnpacked(_T_NullableEntityMemberName_);
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value is null ? null : T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_.CreateFrom(value));
        }
        //##} else {
        private async ValueTask T_RequiredEntityMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = default;
            if (_T_RequiredEntityMemberName_ is null)
            {
                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_>(dataStore);
            }
            else
            {
                await _T_RequiredEntityMemberName_.Pack(dataStore);
                var buffer = _T_RequiredEntityMemberName_.GetBuffer();
                var blob = BlobData.UnsafeWrap(buffer);
                blobId = await dataStore.PutBlob(blob);
            }
            Codec_BlobId_NE.WriteToSpan(_writableLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64).Span, blobId);
        }
        private async ValueTask T_RequiredEntityMemberName__Unpack(IDataStore dataStore, int depth)
        {
            BlobIdV1 blobId = Codec_BlobId_NE.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64).Span);
            if (blobId.IsEmpty)
            {
                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_>(dataStore);
            }
            else
            {
                BlobData? blob = await dataStore.GetBlob(blobId);
                if (blob is null) throw new InvalidDataException($"Blob not found: {blobId}");
                _T_RequiredEntityMemberName_ = T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_.CreateFrom(blob.Value.Memory);
                await _T_RequiredEntityMemberName_.Unpack(dataStore, depth - 1);
            }
        }
        private T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_? _T_RequiredEntityMemberName_ = null;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_ T_RequiredEntityMemberName_
        {
            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeNameSpace_.IT_MemberTypeName_ IT_EntityName_.T_RequiredEntityMemberName_
        {
            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeNameSpace_.MemBlocks.T_MemberTypeName_.CreateFrom(value));
        }
        //##}
        //##break;
        //##case MemberKind.Binary:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableBinaryMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = default;
            if (_T_NullableBinaryMemberName_ is not null)
            {
                var buffer = _T_NullableBinaryMemberName_.Memory;
                var blob = BlobData.UnsafeWrap(buffer);
                blobId = await dataStore.PutBlob(blob);
            }
            Codec_BlobId_NE.WriteToSpan(_writableLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64).Span, blobId);
        }
        private async ValueTask T_NullableBinaryMemberName__Unpack(IDataStore dataStore, int depth)
        {
            _T_NullableBinaryMemberName_ = null;
            BlobIdV1 blobId = Codec_BlobId_NE.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64).Span);
            if (!blobId.IsEmpty)
            {
                BlobData? blob = await dataStore.GetBlob(blobId);
                if (blob is null) throw new InvalidDataException($"Blob not found: {blobId}");
                _T_NullableBinaryMemberName_ = Octets.UnsafeWrap(blob.Value.Memory);
            }
        }
        private Octets? _T_NullableBinaryMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets? T_NullableBinaryMemberName_
        {
            get => IfUnpacked(_T_NullableBinaryMemberName_);
            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_RequiredBinaryMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = default;
            var buffer = _T_RequiredBinaryMemberName_.Memory;
            var blob = BlobData.UnsafeWrap(buffer);
            blobId = await dataStore.PutBlob(blob);
            Codec_BlobId_NE.WriteToSpan(_writableLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64).Span, blobId);
        }
        private async ValueTask T_RequiredBinaryMemberName__Unpack(IDataStore dataStore, int depth)
        {
            _T_RequiredBinaryMemberName_ = Octets.Empty;
            BlobIdV1 blobId = Codec_BlobId_NE.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64).Span);
            if (!blobId.IsEmpty)
            {
                BlobData? blob = await dataStore.GetBlob(blobId);
                if (blob is null) throw new InvalidDataException($"Blob not found: {blobId}");
                _T_RequiredBinaryMemberName_ = Octets.UnsafeWrap(blob.Value.Memory);
            }
        }
        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets T_RequiredBinaryMemberName_
        {
            get => IfUnpacked(_T_RequiredBinaryMemberName_);
            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##default:
        //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
        //##break;
        //##} // switch

        //##}

        public bool Equals(T_EntityName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!_readonlyTotalBlock.Span.SequenceEqual(other._readonlyTotalBlock.Span)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_EntityName_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
        public static bool operator ==(T_EntityName_? left, T_EntityName_? right) => left is not null ? left.Equals(right) : (right is null);
        public static bool operator !=(T_EntityName_? left, T_EntityName_? right) => left is not null ? !left.Equals(right) : (right is not null);

    }
}
